const en = {
    healthPage: {
        title: 'What “Health” means',
        intro: 'The Health Index is an honest measure of how well this server actually runs. Every part is computed by our own pinger over the last 30 days — none of it is set by the owner.',
        overall: 'Overall health',
        outOf: 'out of 100',
        noScore: 'This server doesn’t have a health score yet — it appears once we’ve collected enough pings.',
        componentsTitle: 'How the score is built',
        weight: 'weight',
        contributes: 'contributes',
        pts: 'pts',
        howToImprove: 'How to improve',
        explainLink: 'What does this mean?',
        uMeans: 'Share of the last 30 days the server answered our pings. It’s squared, so instability hurts hard — a server that’s often down is the worst outcome for a player.',
        uImprove: 'Keep the server online and reachable; fix crashes and frequent restarts.',
        aMeans: 'How often someone is actually playing, weighted by average online. The weight levels off around 20 players, so a small cosy server isn’t crushed by a huge one.',
        aImprove: 'Build a regular player base — around 20 steady players already counts as full activity.',
        cMeans: 'How even the activity is from day to day. A server busy every evening scores higher than one that spikes after an ad and then goes quiet.',
        cImprove: 'Aim for steady daily activity rather than one-off spikes.',
        vMeans: 'How current the game version is. Each minor version behind the latest stable costs a little — old versions stop matching players’ clients.',
        vImprove: 'Update to the current stable Vintage Story version.',
        lMeans: 'How long the server has been alive. It reaches full value after a month, rewarding projects that last.',
        lImprove: 'Just keep running — longevity builds itself.',
        formulaTitle: 'The maths, in plain words',
        formulaText: 'The five parts are weighted — uptime and activity matter most (35% and 30%), then rhythm (15%), with version and longevity at 10% each — and combined into a 0–100 score.',
        smoothingText: 'A new server starts near 50 and drifts toward its real score over the first week, so neither a perfect first day nor an empty one is trusted too early.',
        backToServer: '← Back to the server',
        notFound: 'Server not found.',
    },
    compare: {
        title: 'Compare modpacks',
        subtitle: 'Select two servers to compare their mods.',
        serverA: 'Server A',
        serverB: 'Server B',
        common: 'In common',
        versionMismatch: 'Same mod, different version',
        noUnique: 'No unique mods',
        noCommon: 'No mods in common',
        noMods: 'One or both servers have no mods listed.',
    },
    wipes: {
        title: 'Wipe calendar',
        intro: 'Server wipe schedule — upcoming and recent, across all listed servers.',
        metaDesc: 'Vintage Story server wipe calendar — upcoming and recent wipes.',
        empty: 'No upcoming wipes scheduled.',
        emptyRecent: 'No recent wipes.',
        upcoming: 'Upcoming',
        recent: 'Recently wiped',
        today: 'today',
        tomorrow: 'tomorrow',
        yesterday: 'yesterday',
        inDays: 'in {{n}} days',
        daysAgo: '{{n}} days ago',
    },
    wipeBadge: {
        wipe: 'Wipe',
        wiped: 'Wiped',
        nextWipe: 'Next wipe',
        lastWipe: 'Last wipe',
        overdue: 'overdue',
        today: 'today',
        tomorrow: 'tomorrow',
        yesterday: 'yesterday',
        inDays: 'in {{n}}d',
        inWeeks: 'in {{n}}w',
        inMonths: 'in {{n}}mo',
        daysAgo: '{{n}}d ago',
        weeksAgo: '{{n}}w ago',
        monthsAgo: '{{n}}mo ago',
    },
    notif: {
        title: 'Upcoming events',
        empty: 'Nothing upcoming from servers you follow.',
        viewAll: 'View calendar',
    },
    updates: {
        title: 'Site updates',
        metaDesc: 'What\'s new on VS Server List — new features, improvements and fixes.',
        intro: 'Latest changes and announcements for the site.',
        loading: 'Loading updates…',
        empty: 'No updates yet.',
        loadMore: 'Load more',
        category: {
            feature: 'Feature',
            improvement: 'Improvement',
            fix: 'Fix',
            announcement: 'Announcement',
        },
        editor: {
            newTitle: 'New update',
            editTitle: 'Edit update',
            titleField: 'Title',
            bodyField: 'Body (plain text; line breaks preserved)',
            published: 'Published (visible to everyone)',
            draft: 'Draft',
            save: 'Save',
            cancel: 'Cancel',
            edit: 'edit',
            delete: 'delete',
            saved: 'Update saved',
            deleted: 'Update deleted',
            error: 'Could not save. Try again.',
            required: 'Title and body are required.',
            confirmDelete: 'Delete this update?',
        },
    },
    calendar: {
        title: 'Event calendar',
        intro: 'Upcoming server events and wipes. Switch to "My subscriptions" to see only servers you follow.',
        metaDesc: 'Vintage Story server event calendar — festivals, contests, wipes and more.',
        all: 'All',
        mine: 'My subscriptions',
        list: 'List',
        month: 'Month',
        todayBtn: 'Today',
        more: '+{{n}} more',
        allKinds: 'All',
        empty: 'No upcoming events.',
        emptyMine: 'No events from servers you follow. Favorite a server to subscribe.',
        kind: {
            wipe: 'Wipe',
            festival: 'Festival',
            event: 'Event',
            contest: 'Contest',
            update: 'Update',
            other: 'Other',
        },
        recur: {
            none: 'No repeat',
            weekly: 'Weekly',
            monthly: 'Monthly',
        },
        manage: {
            title: 'Server events',
            add: 'Add event',
            empty: 'No events yet.',
            hidden: '(hidden)',
            fldKind: 'Type',
            fldTitle: 'Title',
            fldStarts: 'Starts (UTC)',
            fldEnds: 'Ends (UTC, optional)',
            fldRepeat: 'Repeat',
            fldRepeatUntil: 'Repeat until',
            fldDesc: 'Description',
            save: 'Save',
            saving: 'Saving…',
            delete: 'Delete',
            confirmDelete: 'Delete this event?',
            created: 'Event created',
            updated: 'Event updated',
            deleted: 'Event deleted',
            error: 'Could not save event',
            errRequired: 'Title and start date are required',
        },
    },
    report: {
        report: 'Report',
        titleServer: 'Report this server',
        titleReview: 'Report this review',
        messagePlaceholder: 'Details (optional)',
        submit: 'Submit report',
        thanks: 'Thanks — your report was submitted',
        error: "Couldn't submit the report",
        tooMany: 'Too many reports — please slow down',
        reason: { spam: 'Spam / advertising', abuse: 'Abusive / offensive', fake: 'Fake / misleading', broken: 'Offline / broken', other: 'Other' },
    },
    moderation: {
        nav: 'Moderation',
        title: 'Reports',
        all: 'All',
        statusNew: 'New',
        statusResolved: 'Resolved',
        statusDismissed: 'Dismissed',
        resolve: 'Resolve',
        dismiss: 'Dismiss',
        empty: 'No reports here',
        reviewTarget: 'on a review',
        by: 'by',
    },
    theme: { light: 'Light mode', dark: 'Dark mode' },
    backToTop: 'Back to top',
    favorites: { title: 'My Favorites', add: 'Add to favorites', remove: 'Remove from favorites', added: 'Added to favorites', removed: 'Removed from favorites', error: "Couldn't update favorites" },
    whitelist: {
        applyTitle: 'Join this server',
        applyIntro: 'Request to be added to this whitelisted server. The owner will review your application.',
        playerName: 'Your in-game name',
        messageOptional: 'Message to the owner (optional)',
        submit: 'Send application',
        applied: 'Application sent',
        already: 'You already have an open application for this server',
        nameRequired: 'Enter your in-game name',
        error: 'Something went wrong',
        yourStatus: 'Your application',
        cooldownMsg: 'Your application was rejected. You can re-apply after {{date}}.',
        status: { pending: 'Pending', approved: 'Approved', provisioned: 'Whitelisted', rejected: 'Rejected' },
        ownerTitle: 'Whitelist applications',
        openLabel: 'Accept applications through the site',
        openHint: 'When off, players can\'t apply here — use it if you run your own whitelist process.',
        autoLabel: 'Auto-add approved players via the mod',
        autoHint: 'When on, the game mod adds approved players to the in-game whitelist automatically. Requires our mod installed.',
        noPending: 'No pending applications.',
        history: 'Decision history',
        approve: 'Approve',
        reject: 'Reject',
        messages: 'Messages',
        hideMessages: 'Hide messages',
        messagePlaceholder: 'Write a message…',
        sendMsg: 'Send',
        noMessages: 'No messages yet.',
        ownerTag: 'owner',
    },
    nav: {
        servers: 'Servers',
        about: 'About',
        settings: 'Settings',
        calendar: 'Calendar',
        updates: 'Updates',
        stats: 'Stats',
        report: 'Report',
        alloys: 'Alloys',
        mods: 'Mods',
        atlas: 'Atlas',
        links: 'Links',
        more: 'More',
        recent: 'Recent',
        login: 'Login',
        register: 'Register',
        profile: 'Profile',
        logout: 'Logout',
        viewProfile: "View {{username}}'s profile",
    },
    logout: {
        title: 'Logout',
        confirm: 'Are you sure you want to logout?',
        cancel: 'Cancel',
        success: 'Logged out successfully',
        error: 'Error logging out',
    },
    footer: {
        cookies: 'Cookies used for auth only.',
        privacy: 'Privacy Policy',
        reportBug: 'Report a Bug',
        bgOff: 'no bg',
        bgOn: 'with bg',
        disclaimer: 'Unofficial, community-run server list. Not affiliated with or endorsed by the Vintage Story developers.',
    },
    bottomNav: {
        servers: 'Servers',
        find: 'Find',
        mods: 'Mods',
        profile: 'Profile',
    },
    common: {
        loading: 'Loading...',
        prev: '← Prev',
        next: 'Next →',
        cancel: 'Cancel',
        save: 'Save',
        saving: 'Saving...',
        edit: 'Edit',
        close: 'Close',
        page: 'Page {{page}}',
        players: 'players',
        votes: '{{count}} votes',
        downloads: '{{count}} downloads',
        follows: '{{count}} follows',
        verified: '✓ Verified',
        selfListed: 'Self-listed',
        selfListedTooltip: 'This server was added by its owner. Install our mod or enable master server listing for a verified badge.',
        copied: 'Copied!',
        continue: 'Continue',
    },
    login: {
        title: 'LOGIN',
        subtitle: 'Enter your credentials',
        username: 'Username',
        password: 'Password',
        authenticating: 'Authenticating...',
        submit: '▶ Login',
        forgotPassword: 'Forgot password?',
        noAccount: 'No account?',
        registerHere: 'Register here',
        emailNotConfirmed: 'Please confirm your email before logging in. Check your inbox.',
        invalidCredentials: 'Invalid username or password.',
    },
    register: {
        title: 'REGISTER',
        subtitle: 'Create your account',
        username: 'Username',
        email: 'Email',
        password: 'Password',
        confirmPassword: 'Confirm Password',
        creating: 'Creating account...',
        submit: '▶ Register',
        alreadyHaveAccount: 'Already have an account?',
        logIn: 'Log in',
        fillAllFields: 'Please fill in all fields',
        passwordsNoMatch: 'Passwords do not match',
        errorRegistering: 'Error registering. Username or email may already be taken.',
        checkEmailTitle: 'CHECK YOUR EMAIL',
        emailSent: 'Sent a confirmation link to {{email}}. Click it to activate your account.',
        checkSpam: "Didn't receive it? Check your spam folder.",
        goToLogin: '← Go to Login',
    },
    settings: {
        title: 'SETTINGS',
        profile: 'Profile',
        username: 'Username',
        email: 'Email',
        firstName: 'First Name',
        lastName: 'Last Name',
        bio: 'Bio',
        ingameNickname: 'In-game Nickname',
        ingamePlaceholder: 'Your Vintage Story nickname',
        saveChanges: '✓ Save Changes',
        changePassword: 'Change Password',
        currentPassword: 'Current Password',
        newPassword: 'New Password',
        confirmNewPassword: 'Confirm New Password',
        changePasswordBtn: '✓ Change Password',
        account: 'Account',
        logoutBtn: '← Logout',
        deleteAccount: '✕ Delete Account',
        deleteConfirm: 'Are you sure you want to delete your account? This cannot be undone.',
        passwordsNoMatch: 'New passwords do not match',
        passwordChanged: 'Password changed successfully',
        passwordChangeFailed: 'Failed to change password. Check your current password.',
        saved: 'Settings saved',
        errorUpdating: 'Error updating details',
    },
    forgotPassword: {
        title: 'FORGOT PASSWORD',
        subtitle: 'Enter your email to receive a reset link',
        email: 'Email',
        sending: 'Sending...',
        sendLink: 'Send reset link',
        backToLogin: 'Back to login',
        successMessage: 'If an account with that email exists, a reset link has been sent. Check your inbox. You can request a new link in 24 hours.',
    },
    resetPassword: {
        title: 'RESET PASSWORD',
        subtitle: 'Enter your new password',
        newPassword: 'New password',
        confirmPassword: 'Confirm password',
        invalidLink: 'Invalid reset link.',
        resetting: 'Resetting...',
        submit: 'Reset password',
        successMessage: 'Password has been reset. You can now log in.',
        goToLogin: 'Go to login',
        minLength: 'Password must be at least 8 characters.',
        passwordsNoMatch: 'Passwords do not match.',
        failedReset: 'Failed to reset password. The link may have expired.',
    },
    confirmEmail: {
        loading: { title: 'CONFIRMING', text: 'Please wait...' },
        success: { title: 'EMAIL CONFIRMED', text: 'Your account is now active. You can log in.' },
        error: { title: 'LINK EXPIRED', text: 'The confirmation link has expired or already been used. Please register again.' },
        invalid: { title: 'INVALID LINK', text: 'No confirmation token found in the URL.' },
        goToLogin: '▶ Go to Login',
        registerAgain: '← Register Again',
    },
    about: {
        title: 'ABOUT VS:SERVER:LIST',
        subtitle: 'A place to discover, vote for, and track multiplayer servers for Vintage Story — an indie survival game focused on exploration, building, and lore.',
        findingServerTitle: 'Finding a Server',
        findingServerText: 'Browse the server list on the home page. Use the filters to narrow by game version, whitelist status, or a specific mod. Click a server name to see full details, mods, player history, and reviews.',
        votingTitle: 'Voting',
        votingText: 'Registered users can vote for up to 5 servers per day. Votes help surface active and popular servers. If a server has our mod installed, voting with your in-game nickname can earn you an in-game reward. Vote counts reset at the start of each month; totals from the previous month are saved to the monthly leaderboard.',
        claimingTitle: 'Claiming Your Server',
        claimingText: 'If you run a Vintage Story server, you can claim it here. Open the server\'s detail page and click "Claim this server". You\'ll receive a token — add it to your server description in-game. Ownership is confirmed automatically within 20 minutes at the next sync.',
        modTitle: 'The Mod',
        modText: 'Server owners can install our optional server-side mod. It enables real-time player count updates, shows online player names on the server page, and delivers in-game vote rewards to players automatically.',
        modLink: 'Get the mod →',
        communityTitle: 'Community',
        communityText: 'Questions, suggestions or bug reports? Join our Discord to chat with the team and other players.',
        discordLink: 'Join our Discord →',
        disclaimer: 'This is an unofficial, community-run server list. It is not affiliated with or endorsed by the Vintage Story developers. Vintage Story and its assets belong to their respective owners.',
    },
    links: {
        title: 'Useful Links',
        subtitle: 'Vintage Story resources and our community.',
        ours: 'Our project',
        website: 'Website',
        forums: 'Forums',
        serverList: 'Official Server List',
    },
    stateReport: {
        title: 'State of VS Multiplayer',
        subtitle: 'Monthly report on Vintage Story multiplayer — players, servers, versions and the top of the month.',
        noData: 'No report data yet.',
        older: 'Older',
        newer: 'Newer',
        peak: 'Peak players',
        avgPlayers: 'Avg players',
        activeServers: 'Active servers',
        newServers: 'New servers',
        votes: 'Votes',
        playerTrend: 'Players — peak & average',
        primeTime: 'Prime time (UTC)',
        versions: 'Version mix',
        topServers: 'Top servers',
        risingMods: 'Rising mods',
        reviews: 'New reviews',
        wipes: 'Wipes',
    },
    atlas: {
        title: 'Mod Atlas',
        subtitle: 'A map of the Vintage Story mod ecosystem — reach, followers and downloads across the leading projects.',
        error: 'Could not load the atlas.',
        mods: 'Mods tracked',
        activeMods: 'Active mods',
        downloads: 'Total downloads',
        follows: 'Total followers',
        reachMap: 'Mod map',
        reachMapHint: 'Up to {{n}} leading mods. Axes are percentiles — they keep each metric’s order while spreading projects across the field. Colour shows reach: how many servers run the mod. Click a point to open it.',
        preset_reach: 'Popularity',
        preset_engagement: 'Adoption',
        axisFollows: 'Followers',
        axisDownloads: 'Downloads',
        axisServers: 'Servers',
        topAuthors: 'Top authors',
        modsShort: 'mods',
        downloadsShort: 'downloads',
        hiddenGems: 'Hidden gems',
        hiddenGemsHint: 'Mods running on far more servers than their downloads suggest.',
        topDuos: 'Top mod duos',
        topDuosHint: 'Mods most often installed together.',
        onServers: 'on {{count}} servers',
    },
    mods: {
        title: 'MODS',
        downloadStats: 'Download Stats',
        search: 'Search',
        searchPlaceholder: 'Search mods...',
        noModsFound: 'NO MODS FOUND',
        by: 'by',
    },
    modDetail: {
        notFound: 'MOD NOT FOUND',
        by: 'by',
        updated: 'updated {{date}}',
        viewOnModdb: 'View on mods.vintagestory.at',
        serversUsingMod: 'Servers using this mod',
        total: '{{count}} total',
        noActiveServers: 'No active servers found',
        seeAllServers: 'See all {{count}} servers',
        oftenUsedTogether: 'Often used together',
        ofServers: '{{pct}}% of servers',
        online: '{{online}}/{{max}} online',
    },
    modStats: {
        modsByDownloads: 'Mods by downloads',
        mod: 'Mod',
    },
    modAuthor: {
        notFound: 'AUTHOR NOT FOUND',
        downloadsOverTime: 'Downloads over time',
        mods: 'Mods',
    },
    topAuthors: {
        authorsByDownloads: 'Authors by downloads',
        author: 'Author',
    },
    voteHistory: {
        monthlyResults: 'Monthly Vote Results',
        noHistory: 'NO VOTE HISTORY YET',
    },
    findServer: {
        questionOf: 'Question {{current}} of {{total}}',
        goBack: 'Go back',
        questions: {
            playstyle: {
                text: 'What playstyle do you prefer?',
                survival: 'Survival',
                pvp: 'PvP',
                creative: 'Creative',
                roleplay: 'Roleplay',
                any: 'Any',
            },
            mods: {
                text: 'Do you want mods?',
                vanilla: 'Vanilla',
                modded: 'Modded',
                doesntMatter: "Doesn't matter",
            },
            size: {
                text: 'How big of a community?',
                small: 'Small (1-5)',
                medium: 'Medium (5-20)',
                large: 'Large (20+)',
                anySize: 'Any size',
            },
            password: {
                text: 'Open or private server?',
                open: 'Open to all',
                whitelisted: 'Whitelisted',
                either: 'Either',
            },
        },
    },
    userProfile: {
        servers: 'Servers',
        voteHistory: 'Vote History',
        apiKeyLabel: 'Mod API Key — use in vsserverlistmod.json',
        serverId: 'Server ID: {{id}}',
        hide: 'Hide',
        show: 'Show',
        copy: 'Copy',
        apiKeyCopied: 'API key copied',
    },
    stats: {
        title: 'Multiplayer Stats',
        intro: 'Vintage Story multiplayer statistics in real time: players online, servers, mods and records.',
        metaDesc: 'Live Vintage Story multiplayer statistics: players online, active servers, popular versions and the all-time peak.',
        playersNow: 'playing now',
        serversActive: 'servers with players',
        serversTotal: 'servers listed',
        serversOnline: 'servers online',
        mods: 'mods tracked',
        topVersion: 'most popular',
        record: 'peak record',
        noHistory: 'Charts will appear as daily data accumulates.',
        chartPlayers: 'Players online',
        chartServers: 'Active servers',
        chartVersions: 'Game version share',
        chartMods: 'Top mods by reach',
        chartHours: 'Prime time (UTC)',
        primeTimeDesc: 'Average players online by hour of day (UTC)',
        chartPlaystyle: 'Playstyles',
        chartSize: 'Server sizes',
        chartCountry: 'By country',
        chartLanguage: 'By language',
        chartPlayersVersion: 'Players by version',
        chartHeatmap: 'Activity heatmap',
        heatmapDesc: 'Average players online by day of week and hour (UTC)',
        chartModpack: 'Modpack size',
        modpackDesc: 'Live servers by number of mods (0 = vanilla / not reported)',
        records: 'Records',
        recMostPlayers: 'Most players',
        recMostMods: 'Most mods',
        recOldest: 'Oldest server',
        recMods: 'mods',
        peak: 'peak',
        average: 'average',
    },
    servers: {
        facetHeading: 'servers',
        voteHistory: 'Vote History',
        findServer: 'Find a server for me',
        hideFilters: 'Hide Filters',
        filters: 'Filters',
        search: 'Search',
        searchPlaceholder: 'Search servers...',
        version: 'Version',
        allVersions: 'All versions',
        playstyle: 'Playstyle',
        allPlaystyles: 'All playstyles',
        whitelist: 'Whitelist',
        allServers: 'All servers',
        open: 'Open',
        whitelisted: 'Whitelisted',
        language: 'Language',
        allLanguages: 'All languages',
        sortBy: 'Sort by',
        mostVotes: 'Most votes',
        playersOnline: 'Players online',
        newest: 'Newest',
        topVerified: 'Top (verified first)',
        byHealth: 'By reliability',
        healthLabel: 'Health',
        healthTooltip: 'Server Health Index — measured by us (uptime, activity, rhythm, version, age), not set by the owner.',
        healthU: 'Uptime',
        healthA: 'Activity',
        healthC: 'Rhythm',
        healthV: 'Version',
        healthL: 'Longevity',
        modsFilter: 'Mods',
        anyMod: 'Any mod...',
        selected: '{{count}} selected',
        searchModsPlaceholder: 'Search mods...',
        modsTypeMore: 'Keep typing to narrow…',
        clear: 'Clear ({{count}})',
        resetFilters: 'Reset filters ✕',
        more: 'More ▾',
        less: 'Less ▴',
        votesLeft: 'Votes left:',
        location: 'Location',
        allCountries: 'All countries',
        wipe: 'Wipe',
        any: 'Any',
        noWipes: 'No wipes',
        wipedRecently: 'Wiped recently',
        wipeSoon: 'Wipe coming soon',
        excludeMods: 'Exclude Mods',
        noneExcluded: 'None excluded...',
        excluded: '{{count}} excluded',
        searchModsToExclude: 'Search mods to exclude...',
        tags: 'Tags:',
        showing: 'Showing {{shown}} of {{total}} servers',
        noServersFound: 'NO SERVERS FOUND',
        tryFilters: 'Try adjusting your filters',
        upcomingStrip: 'Upcoming:',
        clearRecent: 'clear',
        share: '⎘ share',
        linkCopied: 'link copied!',
        voteFor: 'Vote for {{name}}?',
        loginRequired: 'Login required',
        votesRemaining: 'You have {{count}} vote{{plural}} remaining today.',
        ingameNicknameLabel: 'Your in-game nickname (optional):',
        nicknamePlaceholder: 'e.g. Steve',
        loginToVote: 'You need an account to vote. Please log in or register.',
        vote: 'Vote',
        logIn: 'Log in',
        votedFor: 'Voted for {{name}}!',
        totalVotes: 'Total votes: {{count}}',
        totalVotesLabel: '{{count}} all-time votes',
        alreadyVoted: 'Already voted today',
        noVotesRemaining: 'No votes remaining today',
        errorFetching: 'Error fetching servers',
        serversCount: '{{count}} servers',
    },
    serverDetail: {
        notFound: 'SERVER NOT FOUND',
        playersOnline: 'Players Online',
        notEnoughData: 'Not enough data for this period',
        activityHeatmap: 'Activity Heatmap',
        owner: 'Owner:',
        version: 'Version',
        playstyle: 'Playstyle',
        players: 'Players',
        location: 'Location',
        languages: 'Languages',
        lastWipe: 'Last Wipe',
        nextWipe: 'Next Wipe',
        onlineNow: 'Online Now ({{count}})',
        serverSettings: 'Server Settings',
        notSet: 'Not set',
        settingsUpdated: 'Settings updated',
        failedToSave: 'Failed to save',
        reviews: 'Reviews',
        editReview: 'Edit your review',
        writeReview: 'Write a review',
        review: 'Review',
        deleteReviewConfirm: 'Delete your review?',
        reviewDeleted: 'Review deleted',
        failedDeleteReview: 'Failed to delete review',
        leaveReview: 'Leave a review',
        reviewPlaceholder: 'Your review (optional)',
        ownerReply: 'Owner reply',
        reply: 'Reply',
        editReply: 'Edit reply',
        replyPlaceholder: 'Your reply (leave empty to remove)',
        noReviews: 'No reviews yet. Be the first!',
        pleaseSelectRating: 'Please select a rating',
        reviewSaved: 'Review saved!',
        failedSaveReview: 'Failed to save review',
        claimServer: 'Claim this server',
        addTokenToDescription: 'Add this token to your server description:',
        ownershipConfirmed: 'Ownership is confirmed within 20 minutes at the next server sync — after that you can remove the token from your description.',
        failedStartClaim: 'Failed to start claim',
        modsCount: 'Mods ({{count}})',
        downloadMd: 'Download mods list as Markdown',
        voteFor: 'Vote for {{name}}?',
        loginRequired: 'Login Required',
        votesRemaining: 'You have {{count}} vote{{plural}} remaining today.',
        ingameNickname: 'In-game nickname (optional)',
        nicknamePlaceholder: 'e.g. Steve',
        loginToVote: 'You need an account to vote. Please log in or register.',
        voteBtn: '▶ Vote',
        logIn: 'Log in',
        votedFor: 'Voted for {{name}}!',
        totalVotes: 'Total votes: {{count}}',
        totalVotesLabel: '{{count}} all-time votes',
        alreadyVoted: 'Already voted today',
        noVotesRemaining: 'No votes remaining today',
        errorFetchingServer: 'Error fetching server',
        submit: '✓ Submit',
        deleteBtn: '✕ Delete',
        autoSyncLabel: 'Auto-sync info from master server',
        autoSyncWarning: 'Master server data will overwrite your edits to name, description, and other info. Continue?',
        ipChangeWarning: 'Changing the address resets verification. Install our mod on the new server to re-verify. Continue?',
        sectionConnection: 'Connection',
        sectionIdentity: 'Identity',
        sectionTagsLocation: 'Tags & Location',
        tagsLabel: 'Tags',
        whitelistedLabel: 'This server has a whitelist',
        whitelistedHint: 'Enables the on-site whitelist application system. Overrides the auto-detected value from the master server.',
        fieldName: 'Server Name',
        fieldDescription: 'Description',
        fieldPlaystyle: 'Playstyle',
        fieldMaxPlayers: 'Max Players',
        fieldGameVersion: 'Game Version',
        fieldIp: 'IP / Hostname',
        fieldPort: 'Port',
        fieldSlug: 'Custom URL',
        slugHint: 'Short readable link, 3–32 chars, lowercase letters, digits and dashes. Leave empty to use the default UUID link.',
        autoSyncDisabledHint: 'Disable auto-sync to edit',
        verifyCta: 'Verify your server: install our mod',
        releaseOwnership: 'Release ownership',
        releaseConfirm: 'Archive this server? It will be hidden from public listings, but you can still see it in your profile. The IP slot will be freed for new registrations. Note: if you are changing IP, do not archive — edit the address in your server settings instead. Only an administrator can bring a server back from the archive.',
        releaseSuccess: 'Server archived',
        mergeTitle: 'Server moved to a new address',
        mergeHint: 'If your server changed IP, we automatically added it as a separate listing. Claim that listing first (the "Claim" button on its page — a code goes in the server description), then pick it here: this listing moves to the new address and keeps its votes, reviews, history and API key. The other listing is archived.',
        mergeSelect: '— pick a listing —',
        mergeAction: 'Move here',
        mergeConfirm: 'Move this server to {{address}}? It keeps all its votes, reviews, history and API key. The other listing will be archived.',
        mergeSuccess: 'Server moved to the new address',
        mergeNotOwner: 'Claim the other listing first',
        ipTakenHint: 'That address is already taken by another listing. If it is your server, claim it and use the move option in settings.',
        archived: 'Archived',
        serverArchived: 'This server has been archived by its owner.',
        rotateApiKey: 'Rotate API key',
        rotateApiKeyConfirm: 'Generate a new API key? The old key will stop working immediately and you must update the mod configuration on your server.',
        rotateApiKeySuccess: 'API key rotated',
        newApiKey: 'New API key',
        ingameSeason: 'In-game Season',
        ingameYear: 'Year {{year}}',
    },
    seasons: {
        spring: 'Spring',
        summer: 'Summer',
        fall: 'Fall',
        winter: 'Winter',
    },
    serverBanner: {
        title: 'Banner',
        upload: 'Upload banner',
        change: 'Change banner',
        remove: 'Remove',
        save: 'Save',
        saving: 'Saving…',
        cropHint: 'Drag to position, scroll or use the slider to zoom. The banner is shown at 3.5:1.',
        uploaded: 'Banner updated',
        removed: 'Banner removed',
        error: 'Could not save banner',
        tooLarge: 'Image must be under 3 MB',
    },
    registerServer: {
        title: 'ADD YOUR SERVER',
        subtitle: 'Register a private or unlisted Vintage Story server',
        fieldName: 'Server Name',
        fieldIp: 'IP / Hostname',
        fieldPort: 'Port',
        fieldDescription: 'Description (optional)',
        fieldPlaystyle: 'Playstyle (optional)',
        fieldMaxPlayers: 'Max Players (optional)',
        fieldGameVersion: 'Game Version (optional)',
        fieldCountry: 'Country (optional)',
        fieldLanguages: 'Languages (optional)',
        confirmOwnership: 'I confirm I own this server',
        submit: 'Register Server',
        submitting: 'Registering...',
        success: 'Server registered!',
        apiKeyTitle: 'Save Your API Key',
        apiKeyDesc: 'Install our mod with this key to verify your server and get live stats. You can also find it later in your profile.',
        limitReached: 'Server limit reached (10 per user)',
        emailNotConfirmed: 'Please confirm your email first',
        conflict: 'A server at this address is already listed.',
        claimInstead: 'Is it yours? Go to server page',
        rateLimited: 'Too many registrations. Please try again in a few minutes.',
        addServer: '+ Add Server',
    },
    alloys: {
        title: 'ALLOY CALCULATOR',
        names: {
            tinBronze: 'Tin Bronze',
            bismuthBronze: 'Bismuth Bronze',
            blackBronze: 'Black Bronze',
            brass: 'Brass',
            leadSolder: 'Lead Solder',
            molybdochalkos: 'Molybdochalkos',
            silverSolder: 'Silver Solder',
            electrum: 'Electrum',
            cupronickel: 'Cupronickel',
        },
        metals: {
            copper: 'Copper',
            tin: 'Tin',
            bismuth: 'Bismuth',
            zinc: 'Zinc',
            gold: 'Gold',
            silver: 'Silver',
            lead: 'Lead',
            nickel: 'Nickel',
        },
        selectAlloy: 'Select Alloy',
        desiredIngots: 'Desired Ingots',
        smeltAt: 'Smelt at {{temp}}',
        smeltAtTier: 'Smelt at {{temp}} · Tier {{tier}}',
        maxPerSmelt: 'max per smelt: {{max}} ingots',
        useMax: 'use max',
        maxWhole: 'max whole',
        slots: '{{count}}/4 slots ✓',
        percentages: 'Percentages',
        maxYield: 'max yield',
        range: 'range: {{min}}–{{max}}%',
        totalValid: 'Total: {{total}}% ✓',
        totalInvalid: 'Total: {{total}}% ⚠ must equal 100%',
        resultTitle: '{{name}} — {{count}} {{unit}}',
        ingot: 'ingot',
        ingots: 'ingots',
        colMetal: 'Metal',
        colPct: '%',
        colUnits: 'Units',
        colIngots: 'Ingots',
        colNuggets: 'Nuggets',
        colSlots: 'Slots (nuggets each)',
    },
}

export default en
