// Página 'VS:SERVER:LIST': https://vsserverlist.com
// Traducido por C4BR3R4 || Última Modificación: 16/JUL/2026 || Registro de Cambios: https://c4br3r4.es/index.php?topic=1498.0

const es = {
    healthPage: {
        title: 'Qué significa la «Salud»',
        intro: 'El Índice de Salud es una medida objetiva del rendimiento real de este servidor. Todos los datos son calculados por nuestro propio sistema de monitorización durante los últimos 30 días; el propietario no interviene en absoluto en su determinación.',
        overall: 'Salud General',
        outOf: 'sobre 100',
        noScore: 'Este servidor aún no tiene una puntuación de salud, que aparecerá cuando hayamos recopilado suficientes consultas de ping.',
        componentsTitle: 'Cómo se calcula la puntuación',
        weight: 'Importancia',
        contributes: 'Aporta',
        pts: 'puntos',
        howToImprove: 'Cómo mejorar',
        explainLink: '¿Qué significa esto?',
        uMeans: 'Porcentaje de los últimos 30 días en los que el servidor ha respondido a nuestros consultas de ping. Se trata de un valor al cuadrado, por lo que la inestabilidad tiene graves consecuencias: un servidor que se cae a menudo es lo peor que le puede pasar a un jugador.',
        uImprove: 'Mantén el servidor en línea y accesible; soluciona los fallos y los reinicios frecuentes.',
        aMeans: 'La frecuencia con la que alguien juega realmente, ponderada por el promedio de jugadores conectados. La ponderación se estabiliza en torno a los 20 jugadores, de modo que un servidor pequeño y acogedor no se vea desbordado por uno enorme.',
        aImprove: 'Crea una base de jugadores habituales: con unos 20 jugadores fijos ya se considera que hay plena actividad.',
        cMeans: 'Cómo es de constante la actividad día tras día. Un servidor que mantiene un nivel de actividad constante todas las semanas obtiene mejores resultados que uno que alcanza un pico después de una campaña publicitaria y luego se queda en silencio.',
        cImprove: 'Intenta mantener una actividad diaria constante en lugar de momentos puntuales de gran intensidad.',
        vMeans: 'Cuál es el nivel de actualización de la versión del juego. Cada versión posterior a la última estable supone un pequeño inconveniente, ya que las versiones antiguas dejan de ser compatibles con los clientes de los jugadores.',
        vImprove: '¡Actualiza a la versión estable actual de Vintage Story!',
        lMeans: 'Cuánto tiempo lleva activo el servidor. Alcanza su valor máximo al cabo de un mes, lo que premia a aquellos proyectos que perduran.',
        lImprove: 'Continúa activo: la longevidad se construye sola.',
        formulaTitle: 'Los cálculos, en pocas palabras',
        formulaText: 'Las cinco partes se ponderan: la disponibilidad y la actividad son los factores más importantes (35% y 30%), seguidos del ritmo (15%), mientras que la versión y la antigüedad cuentan con un 10% cada una. Estas se combinan en una puntuación de 0 a 100.',
        smoothingText: 'Un nuevo servidor empieza con una puntuación cercana a 50 y va acercándose a su puntuación real a lo largo de la primera semana, de modo que no se da por válida ni una puntuación excelente ni una escasa en el primer día.',
        backToServer: '← Volver al servidor',
        notFound: 'No se ha encontrado el servidor.',
    },
    compare: {
        title: 'Comparar por Mods',
        subtitle: 'Selecciona dos servidores para comparar sus mods.',
        serverA: 'Servidor A',
        serverB: 'Servidor B',
        common: 'Mods en Común',
        versionMismatch: 'Mismo mod, con versiones diferentes',
        noUnique: 'Sin mods exclusivos',
        noCommon: 'Sin mods en común',
        noMods: 'En uno de los servidores, o en ambos, no aparece ningún mod.',
    },
    wipes: {
        title: 'Calendario de Reinicios',
        intro: 'Calendario de Reinicios de servidores: próximos y recientes, en todos los servidores de la lista.',
        metaDesc: 'Calendario de Reinicios de servidor de Vintage Story: próximos y recientes.',
        empty: 'No hay reinicios programados.',
        emptyRecent: 'Sin Reinicios Recientes.',
        upcoming: 'Próximamente',
        recent: 'Reiniciado recientemente',
        today: 'hoy',
        tomorrow: 'mañana',
        yesterday: 'ayer',
        inDays: 'en {{n}} días',
        daysAgo: 'hace {{n}} días',
    },
    wipeBadge: {
        wipe: 'Reinicio',
        wiped: 'Reiniciado',
        nextWipe: 'Siguiente Reinicio',
        lastWipe: 'Último Reinicio',
        overdue: 'vencido',
        today: 'hoy',
        tomorrow: 'mañana',
        yesterday: 'ayer',
        inDays: 'en {{n}} días',
        inWeeks: 'en {{n}} semana',
        inMonths: 'en {{n}} mes',
        daysAgo: 'hace {{n}} días',
        weeksAgo: 'hace {{n}} semana',
        monthsAgo: 'hace {{n}} mes',
    },
    notif: {
        title: 'Eventos',
        empty: 'Sin próximos eventos en los servidores que sigues.',
        viewAll: 'Ver Calendario',
    },
    updates: {
        title: 'Novedades de la web',
        metaDesc: 'Novedades de VS Server List: nuevas funciones, mejoras y correcciones.',
        intro: 'Últimas novedades y anuncios sobre la web.',
        loading: 'Cargando actualizaciones…',
        empty: 'De momento no hay novedades.',
        loadMore: 'Mostrar más',
        category: {
            feature: 'Característica',
            improvement: 'Mejora',
            fix: 'Solución',
            announcement: 'Anuncio',
        },
        editor: {
            newTitle: 'Nueva Actualización',
            editTitle: 'Editar Actualización',
            titleField: 'Título',
            bodyField: 'Cuerpo (texto sin formato; se conservan los saltos de línea)',
            published: 'Publicado (visibilidad completa)',
            draft: 'Borrador',
            save: 'Guardar',
            cancel: 'Cancelar',
            edit: 'editar',
            delete: 'eliminar',
            saved: 'Actualización guardada.',
            deleted: 'Actualización eliminada.',
            error: 'No se ha podido guardar. Inténtalo de nuevo.',
            required: 'El título y el cuerpo del texto son obligatorios.',
            confirmDelete: '¿Quieres eliminar esta actualización?',
        },
    },
    calendar: {
        title: 'Calendario de Eventos',
        intro: 'Próximos eventos y reinicios de los servidores. Selecciona «Favoritos» para ver solo los eventos de los servidores que sigues.',
        metaDesc: 'Calendario de eventos del servidor de Vintage Story: torneos, concursos, reinicios y mucho más.',
        all: 'Todo',
        mine: 'Favoritos',
        list: 'Lista',
        month: 'Calendario',
        todayBtn: 'Hoy',
        more: '+{{n}} más',
        allKinds: 'Todo',
        empty: 'No hay eventos programados.',
        emptyMine: 'No hay eventos en los servidores a los que sigues. Añade un servidor cómo favorito para realizar el seguimiento.',
        kind: {
            wipe: 'Reinicio',
            festival: 'Torneo',
            event: 'Evento',
            contest: 'Concurso',
            update: 'Actualización',
            other: 'Otros',
        },
        recur: {
            none: 'Sin Repetición',
            weekly: 'Semanal',
            monthly: 'Mensual',
        },
        manage: {
            title: 'Eventos del Servidor',
            add: 'Añadir Evento',
            empty: 'Todavía no hay eventos.',
            hidden: '(oculto)',
            fldKind: 'Tipo',
            fldTitle: 'Título',
            fldStarts: 'Comienzo (UTC)',
            fldEnds: 'Fin (UTC, opcional)',
            fldRepeat: 'Repetición',
            fldRepeatUntil: 'Repetir hasta',
            fldDesc: 'Descripción',
            save: 'Guardar',
            saving: 'Guardando…',
            delete: 'Eliminar',
            confirmDelete: '¿Quieres eliminar este evento?',
            created: 'Evento creado',
            updated: 'Evento actualizado',
            deleted: 'Evento eliminado',
            error: 'No se ha podido guardar el evento',
            errRequired: 'El título y la fecha de inicio son obligatorios',
        },
    },
    report: {
        report: 'Denunciar',
        titleServer: 'Denunciar este Servidor',
        titleReview: 'Denunciar este Comentario',
        messagePlaceholder: 'Detalles (opcional)',
        submit: 'Procesar denuncia',
        thanks: 'Gracias, tu denuncia ha sido enviada',
        error: 'No se ha podido procesar la denuncia',
        tooMany: 'Demasiados denuncias — por favor, ve más despacio',
        reason: { spam: 'Spam / Publicidad', abuse: 'Insultante / Ofensivo', fake: 'Falso / Engañoso', broken: 'Sin Conexión / No Funciona', other: 'Otros' },
    },
    moderation: {
        nav: 'Moderación',
        title: 'Denuncias',
        all: 'Todo',
        statusNew: 'Nuevo',
        statusResolved: 'Resuelto',
        statusDismissed: 'Desestimado',
        resolve: 'Resolver',
        dismiss: 'Descartar',
        empty: 'Aquí no hay denuncias',
        reviewTarget: 'en un comentario',
        by: 'por',
    },
    theme: { light: 'Tema Claro', dark: 'Tema Oscuro' },
    backToTop: 'Ir Arriba',
    favorites: { title: 'Favoritos', add: 'Añadir a Favoritos', remove: 'Eliminar de Favoritos', added: 'Servidor añadido a Favoritos', removed: 'Servidor eliminado de Favoritos', error: 'No se han podido actualizar los servidores favoritos.' },
    whitelist: {
        applyTitle: 'Conectarse a este Servidor',
        applyIntro: 'Solicita que te añadan a la Lista de Admitidos de este servidor. El propietario revisará tu solicitud.',
        playerName: 'Tu nombre de jugador',
        messageOptional: 'Mensaje para el propietario (opcional)',
        submit: 'Enviar solicitud',
        applied: 'Solicitud enviada.',
        already: 'Ya tienes una solicitud abierta en este servidor.',
        nameRequired: 'Introduce tu nombre de jugador',
        error: 'Se ha producido un error',
        yourStatus: 'Tu solicitud',
        cooldownMsg: 'Tu solicitud ha sido rechazada. Podrás volver a presentarla a partir del {{date}}.',
        status: { pending: 'Pendiente', approved: 'Aceptado', provisioned: 'Admitido', rejected: 'Rechazado' },
        ownerTitle: 'Solicitudes de admisión',
        openLabel: 'Aceptar solicitudes a través de la página web',
        openHint: 'Cuando está desactivada, los jugadores no pueden presentar su solicitud aquí; utilízala si gestionas tu propio procedimiento de Lista de Admitidos.',
        autoLabel: 'Añadir automáticamente a los jugadores aceptados a través del mod',
        autoHint: 'Cuando está activado, el mod del juego añade automáticamente a los jugadores autorizados a la Lista de Admitidos del servidor. Requiere tener instalado nuestro mod.',
        noPending: 'No hay solicitudes pendientes.',
        history: 'Historial de decisiones',
        approve: 'Aceptado',
        reject: 'Rechazado',
        messages: 'Mensajes',
        hideMessages: 'Ocultar mensajes',
        messagePlaceholder: 'Escribir un mensaje…',
        sendMsg: 'Enviar',
        noMessages: 'Aún no hay mensajes.',
        ownerTag: 'Propietario',
    },
    nav: {
        servers: 'Servidores',
        about: 'Acerca de',
        settings: 'Configuración',
        calendar: 'Calendario',
        updates: 'Actualizaciones',
        stats: 'Estadísticas',
        alloys: 'Aleaciones',
        mods: 'Mods',
        more: 'Más',
        recent: 'Visitados',
        login: 'Iniciar Sesión',
        register: 'Registrarse',
        profile: 'Perfil',
        logout: 'Cerrar Sesión',
        viewProfile: 'Ver perfil de {{username}}',
    },
    logout: {
        title: 'Cerrar Sesión',
        confirm: '¿Estás seguro de que quieres cerrar sesión?',
        cancel: 'Cancelar',
        success: 'Se ha cerrado la sesión correctamente',
        error: 'Error al cerrar sesión',
    },
    footer: {
        cookies: 'Cookies usadas con fines de identificación.',
        privacy: 'Política de Privacidad',
        reportBug: 'Informar sobre un Error',
        bgOff: 'Ocultar Fondo',
        bgOn: 'Mostrar Fondo',
        disclaimer: 'Lista de servidores independiente, gestionados por la comunidad. Sin afiliación ni respaldo por parte de los desarrolladores de Vintage Story.',
    },
    bottomNav: {
        servers: 'Servidores',
        find: 'Buscar',
        mods: 'Mods',
        profile: 'Perfil',
    },
    common: {
        loading: 'Cargando…',
        prev: '← Anterior',
        next: 'Siguiente →',
        cancel: 'Cancelar',
        save: 'Guardar',
        saving: 'Guardando…',
        edit: 'Editar',
        close: 'Cerrar',
        page: 'Página {{page}}',
        players: 'jugadores',
        votes: '| {{count}} votos',
        downloads: '{{count}} descargas',
        follows: '| {{count}} seguidores',
        verified: '✓ Verificado',
        selfListed: 'Autorregistrado',
        selfListedTooltip: 'Este servidor lo ha añadido su propietario. Instala nuestro mod o activa el listado de servidores principales para obtener la insignia de verificación.',
        copied: '¡Copiado!',
        continue: 'Continuar',
    },
    login: {
        title: 'INICIO DE SESIÓN',
        subtitle: 'Introduce tus datos de acceso',
        username: 'Nombre de Usuario',
        password: 'Contraseña',
        authenticating: 'Verificando identidad…',
        submit: '▶ Iniciar Sesión',
        forgotPassword: '¿Has olvidado la contraseña?',
        noAccount: '¿No tienes cuenta?',
        registerHere: 'Regístrate aquí',
        emailNotConfirmed: 'Confirma tu correo electrónico antes de iniciar sesión. Revisa tu bandeja de entrada.',
        invalidCredentials: 'Nombre de usuario o contraseña incorrectos.',
    },
    register: {
        title: 'REGISTRO',
        subtitle: 'Crea tu cuenta',
        username: 'Nombre de Usuario',
        email: 'Email',
        password: 'Contraseña',
        confirmPassword: 'Confirmar Contraseña',
        creating: 'Creando cuenta…',
        submit: '▶ Registrarse',
        alreadyHaveAccount: '¿Ya tienes una cuenta?',
        logIn: 'Iniciar Sesión',
        fillAllFields: 'Rellena todos los campos',
        passwordsNoMatch: 'Las contraseñas no coinciden',
        errorRegistering: 'Error al registrarse. Es posible que el nombre de usuario o la dirección de correo electrónico ya estén en uso.',
        checkEmailTitle: 'COMPRUEBA TU EMAIL',
        emailSent: 'Te hemos enviado un enlace de confirmación a {{email}}. Pulsa aquí para activar tu cuenta.',
        checkSpam: '¿No lo has recibido? Comprueba la carpeta de correo no deseado.',
        goToLogin: '← Ir a Inicio de Sesión',
    },
    settings: {
        title: 'CONFIGURACIÓN',
        profile: 'Perfil',
        username: 'Nombre de Usuario',
        email: 'Email',
        firstName: 'Nombre',
        lastName: 'Apellido',
        bio: 'Biografía',
        ingameNickname: 'Apodo en el Juego',
        ingamePlaceholder: 'Tu apodo en Vintage Story',
        saveChanges: '✓ Guardar Cambios',
        changePassword: 'Cambiar Contraseña',
        currentPassword: 'Contraseña Actual',
        newPassword: 'Contraseña Nueva',
        confirmNewPassword: 'Confirmar Contraseña Nueva',
        changePasswordBtn: '✓ Cambiar Contraseña',
        account: 'Cuenta',
        logoutBtn: '← Cerrar Sesión',
        deleteAccount: '✕ Eliminar Cuenta',
        deleteConfirm: '¿Estás seguro de que quieres eliminar tu cuenta? Esta acción es irreversible.',
        passwordsNoMatch: 'Las nuevas contraseñas no coinciden',
        passwordChanged: 'La contraseña se ha cambiado correctamente',
        passwordChangeFailed: 'No se ha podido cambiar la contraseña. Comprueba tu contraseña actual.',
        saved: 'Configuración guardada',
        errorUpdating: 'Error al actualizar los datos',
    },
    forgotPassword: {
        title: '¿HAS OLVIDADO TU CONTRASEÑA?',
        subtitle: 'Introduce tu correo electrónico para recibir un enlace para restablecerlo.',
        email: 'Email',
        sending: 'Enviando…',
        sendLink: 'Enviar enlace de restablecimiento',
        backToLogin: 'Volver a iniciar sesión',
        successMessage: 'Si existe una cuenta con esa dirección de correo electrónico, recibirás un enlace para restablecer la contraseña. Revisa tu bandeja de entrada. Podrás solicitar un nuevo enlace dentro de 24 horas.',
    },
    resetPassword: {
        title: 'RESTABLECER CONTRASEÑA',
        subtitle: 'Introduce la nueva contraseña',
        newPassword: 'Nueva Contraseña',
        confirmPassword: 'Confirmar Contraseña',
        invalidLink: 'Enlace de restablecimiento no válido.',
        resetting: 'Restableciendo…',
        submit: 'Restablecer contraseña',
        successMessage: 'Se ha restablecido la contraseña. Ya puedes iniciar sesión.',
        goToLogin: 'Ir a Iniciar Sesión',
        minLength: 'La contraseña debe tener al menos 8 caracteres.',
        passwordsNoMatch: 'Las contraseñas no coinciden.',
        failedReset: 'No se ha podido restablecer la contraseña. Es posible que el enlace haya caducado.',
    },
    confirmEmail: {
        loading: { title: 'CONFIRMANDO', text: 'Por favor, espera…' },
        success: { title: 'EMAIL CONFIRMADO', text: 'Tu cuenta ya está activa. Ya puedes iniciar sesión.' },
        error: { title: 'ENLACE CADUCADO', text: 'El enlace de confirmación ha caducado o ya se ha utilizado. Vuelve a registrarte.' },
        invalid: { title: 'ENLACE NO VÁLIDO', text: 'No se ha encontrado ningún código de confirmación en la URL.' },
        goToLogin: '▶ Ir a Iniciar Sesión',
        registerAgain: '← Volver a Registrarse',
    },
    about: {
        title: 'ACERCA DE VS:SERVER:LIST',
        subtitle: 'Un lugar para descubrir, votar y seguir servidores multijugador de Vintage Story, un juego «independiente» de supervivencia, centrado en la exploración, la construcción y la historia.',
        findingServerTitle: 'Buscar un Servidor',
        findingServerText: 'Explora la lista de servidores en la página de inicio. Utiliza los filtros para acotar la búsqueda por versión, público o privado, o un mod concreto. Pulsa sobre el nombre de un servidor para ver todos los detalles, los mods, el registro de jugadores y los comentarios.',
        votingTitle: 'Votación',
        votingText: 'Los usuarios registrados pueden votar un máximo de 5 servidores al día. Los votos ayudan a destacar los servidores más activos y populares. Si un servidor tiene instalado nuestro mod, votar con tu apodo del juego te puede dar derecho a una recompensa dentro del juego. El recuento de votos se reinicia a principios de cada mes; los totales del mes anterior se guardan en la clasificación mensual.',
        claimingTitle: 'Reclamar tu Servidor',
        claimingText: 'Si administras un servidor de Vintage Story, puedes reclamarlo aquí. Abre la página de detalles del servidor y pulsa sobre «Reclamar este Servidor». Recibirás un código; añádelo a la descripción de tu servidor dentro del juego. La propiedad se confirmará automáticamente en un plazo de 20 minutos, en la siguiente sincronización.',
        modTitle: 'El Mod',
        modText: 'Los propietarios de los servidores pueden instalar nuestro módulo opcional del lado del servidor. Este permite actualizar el recuento de jugadores en tiempo real, muestra los nombres de los jugadores conectados en la página del servidor y entrega automáticamente a los jugadores las recompensas por votar dentro del juego.',
        modLink: 'Consigue el mod →',
        disclaimer: 'Lista de servidores independiente, gestionados por la comunidad. Sin afiliación ni respaldo por parte de los desarrolladores de Vintage Story. Vintage Story y sus contenidos pertenecen a sus respectivos propietarios.',
    },
    mods: {
        title: 'MODS',
        downloadStats: 'Mods por Cantidad de Descargas',
        search: 'Buscar',
        searchPlaceholder: 'Buscar mods…',
        noModsFound: 'NO SE HAN ENCONTRADO MODS',
        by: 'por',
    },
    modDetail: {
        notFound: 'MOD NO ENCONTRADO',
        by: 'por',
        updated: 'actualizado {{date}}',
        viewOnModdb: 'Ver en mods.vintagestory.at',
        serversUsingMod: 'Servidores que utilizan este mod',
        total: '{{count}} total',
        noActiveServers: 'No se han encontrado servidores activos',
        seeAllServers: 'Ver todos los {{count}} servidores',
        oftenUsedTogether: 'Usado junto con los siguientes mods',
        ofServers: 'El {{pct}}% de los servidores',
        online: 'Jugadores {{online}}/{{max}}',
    },
    modStats: {
        modsByDownloads: 'Mods por Cantidad de Descargas',
        mod: 'Mod',
    },
    modAuthor: {
        notFound: 'AUTOR NO ENCONTRADO',
        downloadsOverTime: 'Descargas a lo largo del tiempo',
        mods: 'Mods',
    },
    topAuthors: {
        authorsByDownloads: 'Autores por número de descargas',
        author: 'Autor',
    },
    voteHistory: {
        monthlyResults: 'Votaciones por Meses',
        noHistory: 'AÚN NO HAY REGISTRO DE VOTACIONES',
    },
    findServer: {
        questionOf: 'Pregunta {{current}} de {{total}}',
        goBack: 'Volver',
        questions: {
            playstyle: {
                text: '¿Qué estilo de juego prefieres?',
                survival: 'Supervivencia',
                pvp: 'PvP',
                creative: 'Creativo',
                roleplay: 'Roleplay',
                any: 'Cualquiera',
            },
            mods: {
                text: '¿Quieres que tenga Mods?',
                vanilla: 'No, sin mods',
                modded: 'Si, que use mods',
                doesntMatter: 'No me Importa',
            },
            size: {
                text: '¿Qué tamaño de comunidad buscas?',
                small: 'Pequeño (1-5)',
                medium: 'Mediano (5-20)',
                large: 'Grande (más de 20)',
                anySize: 'Cualquiera',
            },
            password: {
                text: '¿Servidor público o privado?',
                open: 'Público, puede conectarse cualquiera',
                whitelisted: 'Privado, sólo con invitación',
                either: 'Ambos',
            },
        },
    },
    userProfile: {
        servers: 'Servidores',
        voteHistory: 'Registro de Votos',
        apiKeyLabel: 'Clave API de Mod: utilízala en vsserverlistmod.json',
        serverId: 'ID del Servidor: {{id}}',
        hide: 'Ocultar',
        show: 'Mostrar',
        copy: 'Copiar',
        apiKeyCopied: 'Clave API copiada',
    },
    stats: {
        title: 'Estadísticas multijugador',
        intro: 'Estadísticas multijugador de Vintage Story en tiempo real: jugadores conectados, servidores, mods y logros.',
        metaDesc: 'Estadísticas multijugador de Vintage Story en directo: jugadores conectados, servidores activos, versiones más populares y el máximo histórico.',
        playersNow: 'Jugando',
        serversActive: 'Servidores con Jugadores',
        serversTotal: 'Servidores',
        serversOnline: 'Servidores Activos',
        mods: 'Mods',
        topVersion: 'Más Popular',
        record: 'Registro de Jugadores',
        noHistory: 'Los gráficos aparecerán a medida que se vayan acumulando los datos diarios.',
        chartPlayers: 'Jugadores Conectados',
        chartServers: 'Servidores Activos',
        chartVersions: 'Cuota de Versiones',
        chartMods: 'Mods más populares por número de seguidores',
        chartHours: 'Horario de máxima audiencia (UTC)',
        primeTimeDesc: 'Promedio de jugadores conectados por hora del día (UTC)',
        chartPlaystyle: 'Estilos de Juego',
        chartSize: 'Tamaños de los Servidores',
        chartCountry: 'Por País',
        chartLanguage: 'Por Idioma',
        chartPlayersVersion: 'Jugadores por Versión',
        chartHeatmap: 'Mapa de Actividad',
        heatmapDesc: 'Promedio de jugadores conectados por día y hora (UTC)',
        chartModpack: 'Por Cantidad de Mods',
        modpackDesc: 'Servidores activos por cantidad de mods (0 = versión original / desconocido)',
        records: 'Registros',
        recMostPlayers: 'Con Más Jugadores',
        recMostMods: 'Con Más Mods',
        recOldest: 'Servidor Más Antiguo',
        recMods: 'mods',
        peak: 'pico',
        average: 'media',
    },
    servers: {
        facetHeading: 'Servidores',
        voteHistory: 'Registro de Votos',
        findServer: 'Encontrar un Servidor',
        hideFilters: 'Ocultar Filtros',
        filters: 'Filtros',
        search: 'Buscar',
        searchPlaceholder: 'Buscar servidor…',
        version: 'Versión',
        allVersions: 'Todas',
        playstyle: 'Estilo de Juego',
        allPlaystyles: 'Todos los Estilos',
        whitelist: 'Admisión',
        allServers: 'Todos',
        open: 'Público',
        whitelisted: 'Privado',
        language: 'Idioma',
        allLanguages: 'Todos',
        sortBy: 'Ordenación',
        mostVotes: 'Más Votados',
        playersOnline: 'Más Jugadores',
        newest: 'Más Recientes',
        topVerified: 'Mejor Calificados (verificados primero)',
        byHealth: 'Mayor Salud',
        healthLabel: 'Salud',
        healthTooltip: 'La salud del servidor no lo establece el propietario, lo calculamos nosotros (disponibilidad, actividad, ritmo, versión y antigüedad).',
        healthU: 'Disponibilidad',
        healthA: 'Actividad',
        healthC: 'Ritmo',
        healthV: 'Versión',
        healthL: 'Antigüedad',
        modsFilter: 'Mods',
        anyMod: 'Cualquiera',
        selected: '{{count}} seleccionado',
        searchModsPlaceholder: 'Buscar mods…',
        modsTypeMore: 'Sigue escribiendo para acotar la búsqueda…',
        clear: 'Limpiar ({{count}})',
        resetFilters: 'Restablecer filtros ✕',
        more: 'Más ▾',
        less: 'Menos ▴',
        votesLeft: 'Votos restantes:',
        location: 'Ubicación',
        allCountries: 'Todos los Países',
        wipe: 'Reinicio (wipe)',
        any: 'Cualquiera',
        noWipes: 'Sin Reiniciar',
        wipedRecently: 'Reiniciado Recientemente',
        wipeSoon: 'Siguiente Reinicio',
        excludeMods: 'Excluir Mods',
        noneExcluded: 'Sin Exclusiones…',
        excluded: '{{count}} mods excluidos',
        searchModsToExclude: 'Buscar mods a excluir…',
        tags: 'Etiquetas:',
        showing: 'Mostrando {{shown}} de {{total}} servidores',
        noServersFound: 'NO SE HAN ENCONTRADO SERVIDORES',
        tryFilters: 'Prueba a ajustar tus filtros',
        upcomingStrip: 'Próximamente:',
        clearRecent: 'Retirar Todos',
        share: '⎘ compartir',
        linkCopied: '¡Enlace Copiado!',
        voteFor: '¿Votar por {{name}}?',
        loginRequired: 'Es necesario Iniciar Sesión',
        votesRemaining: 'Te quedan {{count}} voto{{plural}}.',
        ingameNicknameLabel: 'Tu apodo en el juego (opcional):',
        nicknamePlaceholder: 'ej. YoMismo',
        loginToVote: 'Necesitas una cuenta para votar. Inicia sesión o regístrate.',
        vote: 'Votar',
        logIn: 'Iniciar Sesión',
        votedFor: '¡Has Votado por {{name}}!',
        totalVotes: 'Votos Totales: {{count}}',
        totalVotesLabel: '{{count}} votos acumulados',
        alreadyVoted: 'Hoy ya he votado',
        noVotesRemaining: 'No quedan votos para hoy',
        errorFetching: 'Error al conectar con los servidores',
        serversCount: '{{count}} servidores',
    },
    serverDetail: {
        notFound: 'SERVIDOR NO ENCONTRADO',
        playersOnline: 'Conexión de Jugadores',
        notEnoughData: 'No hay datos suficientes durante este periodo.',
        activityHeatmap: 'Mapa de Actividad',
        owner: 'Propietario:',
        version: 'Versión',
        playstyle: 'Estilo de Juego',
        players: 'Jugadores',
        location: 'Ubicación',
        languages: 'Idiomas',
        lastWipe: 'Último Reinicio',
        nextWipe: 'Siguiente Reinicio',
        onlineNow: 'Jugadores Conectados ({{count}})',
        serverSettings: 'Configuración del Servidor',
        notSet: 'Sin Definir',
        settingsUpdated: 'Configuración actualizada',
        failedToSave: 'No se ha podido guardar',
        reviews: 'Comentarios',
        editReview: 'Edita tu Comentario',
        writeReview: 'Escribe una Comentario',
        review: 'Añadir Comentario',
        deleteReviewConfirm: '¿Quieres eliminar tu comentario?',
        reviewDeleted: 'Comentario eliminado',
        failedDeleteReview: 'No se ha podido eliminar el comentario',
        leaveReview: 'Deja un comentario',
        reviewPlaceholder: 'Tu Comentario (opcional)',
        ownerReply: 'Respuesta del Propietario',
        reply: 'Responder',
        editReply: 'Editar Respuesta',
        replyPlaceholder: 'Tu Respuesta (dejar en blanco para eliminar)',
        noReviews: 'Aún no hay comentarios. ¡Puedes ser el primero!',
        pleaseSelectRating: 'Selecciona una Valoración',
        reviewSaved: '¡Comentario guardado!',
        failedSaveReview: 'No se ha podido guardar el comentario',
        claimServer: 'Reclamar este Servidor',
        addTokenToDescription: 'Añade este código a la descripción de tu servidor:',
        ownershipConfirmed: 'La propiedad se confirmará en un plazo de 20 minutos, en la próxima sincronización del servidor; a partir de ese momento, podrás eliminar el código de tu descripción.',
        failedStartClaim: 'No se ha podido iniciar la reclamación',
        modsCount: 'Mods ({{count}})',
        downloadMd: 'Descargar la lista de mods en formato Markdown',
        voteFor: '¿Votar por {{name}}?',
        loginRequired: 'Es necesario Iniciar Sesión',
        votesRemaining: 'Te quedan {{count}} voto{{plural}}.',
        ingameNickname: 'Apodo en el Juego (opcional)',
        nicknamePlaceholder: 'Ej. YoMismo',
        loginToVote: 'Necesitas una cuenta para votar. Inicia sesión o regístrate.',
        voteBtn: '▶ Votar',
        logIn: 'Iniciar Sesión',
        votedFor: '¡Has votado por {{name}}!',
        totalVotes: 'Votos Totales: {{count}}',
        totalVotesLabel: '{{count}} votos acumulados',
        alreadyVoted: 'Ya has votado hoy',
        noVotesRemaining: 'Hoy no te quedan votos',
        errorFetchingServer: 'Error al acceder al servidor',
        submit: '✓ Aceptar',
        deleteBtn: '✕ Eliminar',
        autoSyncLabel: 'Sincronizar la información del servidor automáticamente.',
        autoSyncWarning: 'La información introducida manualmente, se sobrescribirá por la información configurada en el servidor. ¿Quieres continuar?',
        ipChangeWarning: 'Al cambiar la dirección, hay que volver a realizar el proceso de verificación. Instala nuestro mod en el servidor, para volver a verificar. ¿Continuar?',
        sectionConnection: 'Conexión',
        sectionIdentity: 'Identidad',
        sectionTagsLocation: 'Etiquetas y Ubicación',
        tagsLabel: 'Etiquetas',
        whitelistedLabel: 'Este servidor cuenta con una Lista de Admitidos',
        whitelistedHint: 'Activa el sistema de Lista de Admitidos de la aplicación local. Anula el valor detectado automáticamente por el servidor principal.',
        fieldName: 'Nombre del Servidor',
        fieldDescription: 'Descripción',
        fieldPlaystyle: 'Estilo de Juego',
        fieldMaxPlayers: 'Capacidad',
        fieldGameVersion: 'Versión',
        fieldIp: 'IP / Nombre de Host',
        fieldPort: 'Puerto',
        fieldSlug: 'URL Personalizada',
        slugHint: 'Enlace corto y fácil de leer, de 3 a 32 caracteres, con letras minúsculas, números y guiones. Déjar en blanco para utilizar el enlace UUID predeterminado.',
        autoSyncDisabledHint: 'Desactivar la sincronización para editar.',
        verifyCta: 'Verifica tu servidor: instala nuestro mod',
        releaseOwnership: 'Liberar la Propiedad del Servidor',
        releaseConfirm: '¿Archivar este servidor? Quedará oculto en la Lista de Servidores Públicos, pero podrás seguir viéndolo en tu perfil. La dirección IP quedará libre y disponible para nuevos registros. Aviso: si vas a cambiar la IP, no archives — edita la dirección en los ajustes del servidor. Solo un administrador puede sacar un servidor del archivo.',
        releaseSuccess: 'Servidor Archivado',
        mergeTitle: 'El servidor se mudó a una nueva dirección',
        mergeHint: 'Si tu servidor cambió de IP, lo añadimos automáticamente como una entrada aparte. Reclama primero esa entrada (el botón «Reclamar» en su página — el código va en la descripción del servidor) y luego selecciónala aquí: esta entrada se mudará a la nueva dirección y conservará sus votos, reseñas, historial y clave API. La otra entrada se archivará.',
        mergeSelect: '— elige una entrada —',
        mergeAction: 'Mudar aquí',
        mergeConfirm: '¿Mudar este servidor a {{address}}? Conservará todos sus votos, reseñas, historial y clave API. La otra entrada será archivada.',
        mergeSuccess: 'Servidor mudado a la nueva dirección',
        mergeNotOwner: 'Reclama primero la otra entrada',
        ipTakenHint: 'Esa dirección ya está ocupada por otra entrada. Si es tu servidor, reclámala y usa la opción de mudanza en los ajustes.',
        archived: 'Archivado',
        serverArchived: 'Este servidor ha sido archivado por su propietario.',
        rotateApiKey: 'Renovar la Clave API',
        rotateApiKeyConfirm: '¿Quieres generar una nueva clave API? La clave anterior dejará de funcionar inmediatamente y deberás actualizar la configuración del mod en tu servidor.',
        rotateApiKeySuccess: 'Se ha renovado la Clave API',
        newApiKey: 'Nueva Clave API',
        ingameSeason: 'Estación del Juego',
        ingameYear: 'Año {{year}}',
    },
    seasons: {
        spring: 'Primavera',
        summer: 'Verano',
        fall: 'Otoño',
        winter: 'Invierno',
    },
    serverBanner: {
        title: 'Enseña',
        upload: 'Subir Enseña',
        change: 'Cambiar Enseña',
        remove: 'Eliminar',
        save: 'Guardar',
        saving: 'Guardando…',
        cropHint: 'Arrastra para colocar, desplázate o utiliza el control deslizante para ampliar o reducir. La enseña se muestra en una proporción de 3,5/1.',
        uploaded: 'Enseña actualizada',
        removed: 'Enseña eliminada',
        error: 'No se ha podido guardar la enseña',
        tooLarge: 'La imagen debe tener un tamaño inferior a 3 MB',
    },
    registerServer: {
        title: 'AÑADE TU SERVIDOR',
        subtitle: 'Registrar un servidor de Vintage Story privado o sin publicar.',
        fieldName: 'Nombre del Servidor',
        fieldIp: 'IP / Nombre de Host',
        fieldPort: 'Puerto',
        fieldDescription: 'Descripción (opcional)',
        fieldPlaystyle: 'Estilo de Juego (opcional)',
        fieldMaxPlayers: 'Capacidad (opcional)',
        fieldGameVersion: 'Versión (opcional)',
        fieldCountry: 'País (opcional)',
        fieldLanguages: 'Idiomas (opcional)',
        confirmOwnership: 'Confirmo que soy el propietario de este servidor.',
        submit: 'Registrar Servidor',
        submitting: 'Registrando…',
        success: '¡Servidor registrado!',
        apiKeyTitle: 'Guarda tu Clave API',
        apiKeyDesc: 'Instala nuestro mod con esta clave para verificar tu servidor y obtener estadísticas en tiempo real. También podrás encontrarlo más adelante en tu perfil.',
        limitReached: 'Se ha alcanzado el límite de servidores (10 por usuario)',
        emailNotConfirmed: 'Por favor, confirma primero tu correo electrónico',
        conflict: 'Ya hay un servidor registrado con esta dirección.',
        claimInstead: '¿Es tuyo? Ve a la página del servidor.',
        rateLimited: 'Se han producido demasiados intentos de registro. Inténtalo de nuevo dentro de unos minutos.',
        addServer: '+ Añadir Servidor',
    },
    alloys: {
        title: 'CALCULADORA DE ALEACIONES',
        names: {
            tinBronze: 'Bronce Estañado',
            bismuthBronze: 'Bronce de Bismuto',
            blackBronze: 'Bronce Negro',
            brass: 'Latón',
            leadSolder: 'Soldadura de Plomo',
            molybdochalkos: 'Plomo Cobrizado',
            silverSolder: 'Soldadura de Plata',
            electrum: 'Oro Blanco',
            cupronickel: 'Cuproníquel',
        },
        metals: {
            copper: 'Cobre',
            tin: 'Estaño',
            bismuth: 'Bismuto',
            zinc: 'Cinc',
            gold: 'Oro',
            silver: 'Plata',
            lead: 'Plomo',
            nickel: 'Níquel',
        },
        selectAlloy: 'Seleccionar la Aleación',
        desiredIngots: 'Lingotes deseados',
        smeltAt: 'Enfriar a {{temp}}',
        smeltAtTier: 'Enfriar a {{temp}} · Nivel {{tier}}',
        maxPerSmelt: 'Procesamiento máximo: {{max}} lingotes',
        useMax: 'Máximo',
        maxWhole: 'Totalidad',
        slots: '{{count}}/4 ranuras ✓',
        percentages: 'Porcentajes',
        maxYield: 'Máximo Aprovechamiento',
        range: 'Rango: {{min}}–{{max}}%',
        totalValid: 'Total: {{total}}% ✓',
        totalInvalid: 'Total: {{total}}% ⚠ debe ser igual al 100%',
        resultTitle: '{{name}} — {{count}} {{unit}}',
        ingot: 'lingote',
        ingots: 'lingotes',
        colMetal: 'Metal',
        colPct: '%',
        colUnits: 'Unidades',
        colIngots: 'Lingotes',
        colNuggets: 'Pepitas',
        colSlots: 'Ranuras (por Pepita)',
    },
}

export default es
